<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-05T08:05:04 IST" name="Suite" finished-at="2024-11-05T08:05:12 IST" duration-ms="7863">
    <groups>
    </groups>
    <test started-at="2024-11-05T08:05:04 IST" name="Test" finished-at="2024-11-05T08:05:12 IST" duration-ms="7863">
      <class name="com.vcentry.testcase.LoginTest">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:com.vcentry.testcase.LoginTest@30b34287]" started-at="2024-11-05T08:05:04 IST" name="beforeSuite" finished-at="2024-11-05T08:05:04 IST" duration-ms="145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="initilize()[pri:0, instance:com.vcentry.testcase.LoginTest@30b34287]" started-at="2024-11-05T08:05:04 IST" name="initilize" finished-at="2024-11-05T08:05:07 IST" duration-ms="2780" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilize -->
        <test-method is-config="true" signature="launchUrl()[pri:0, instance:com.vcentry.testcase.LoginTest@30b34287]" started-at="2024-11-05T08:05:07 IST" name="launchUrl" finished-at="2024-11-05T08:05:09 IST" duration-ms="1571" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchUrl -->
        <test-method signature="LoginWithInvalidCredentials(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.vcentry.testcase.LoginTest@30b34287]" started-at="2024-11-05T08:05:09 IST" name="LoginWithInvalidCredentials" data-provider="InvalidLogin" finished-at="2024-11-05T08:05:10 IST" duration-ms="1249" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Please enter a correct username and password. Note that both fields may be case-sensitive.]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please enter a correct username and password. Note that both fields may be case-sensitive.] but found [Register]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please enter a correct username and password. Note that both fields may be case-sensitive.] but found [Register]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.vcentry.pages.LoginPage.verifyHomePage(LoginPage.java:34)
at com.vcentry.testcase.LoginTest.LoginWithInvalidCredentials(LoginTest.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWithInvalidCredentials -->
        <test-method signature="LoginWithValidCredentials(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.vcentry.testcase.LoginTest@30b34287]" started-at="2024-11-05T08:05:11 IST" name="LoginWithValidCredentials" data-provider="ValidLogin" finished-at="2024-11-05T08:05:12 IST" duration-ms="1401" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[sutharsan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Selenium]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[sutharsan]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [sutharsan] but found [Register]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [sutharsan] but found [Register]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.vcentry.pages.LoginPage.verifyHomePage(LoginPage.java:34)
at com.vcentry.testcase.LoginTest.LoginWithValidCredentials(LoginTest.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWithValidCredentials -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:com.vcentry.testcase.LoginTest@30b34287]" started-at="2024-11-05T08:05:12 IST" name="afterTest" finished-at="2024-11-05T08:05:12 IST" duration-ms="126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.vcentry.testcase.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
